# Generated by Django 5.1.6 on 2025-09-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
