# Generated by Django 5.1.6 on 2025-09-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0003_patient_address_patient_allergies_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_file',
            name='doctor',
        ),
    ]
