# Generated by Django 5.1.6 on 2025-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0004_remove_patient_file_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
