# Generated by Django 5.1.6 on 2026-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0006_patient_visit_patient_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
