# Generated by Django 5.1.6 on 2026-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0007_doctor_address_doctor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_vitals',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient_vitals',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
