# Generated by Django 5.1.6 on 2026-07-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0008_patient_vitals_height_patient_vitals_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_vitals',
            old_name='blood_pressure',
            new_name='bp',
        ),
        migrations.RenameField(
            model_name='patient_vitals',
            old_name='heart_rate',
            new_name='pulse',
        ),
        migrations.RenameField(
            model_name='patient_vitals',
            old_name='temperature',
            new_name='temp',
        ),
    ]
