# Generated by Django 5.2.4 on 2026-08-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0009_rename_blood_pressure_patient_vitals_bp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_file',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_doctor', to='medirec.doctor'),
        ),
        migrations.AlterField(
            model_name='patient_file',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='medirec.patient'),
        ),
    ]
