# Generated by Django 5.2.4 on 2026-08-15 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medirec', '0010_patient_file_doctor_alter_patient_file_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_file',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='medirec.patient'),
        ),
    ]
